// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/admin/add-quantity-column': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/add-quantity-column.get').default>>>>
    }
    '/api/admin/auth-credentials-info': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/auth-credentials-info.get').default>>>>
    }
    '/api/admin/auto-cleanup-failed-orders': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/auto-cleanup-failed-orders.post').default>>>>
    }
    '/api/admin/categories/available': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/categories/available.get').default>>>>
    }
    '/api/admin/chart-stats': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/chart-stats.get').default>>>>
    }
    '/api/admin/check-transaction': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/check-transaction.get').default>>>>
    }
    '/api/admin/check-transactions-table': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/check-transactions-table.get').default>>>>
    }
    '/api/admin/cleanup-not-found-transactions': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/cleanup-not-found-transactions.get').default>>>>
    }
    '/api/admin/cleanup-pending-transactions': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/cleanup-pending-transactions.get').default>>>>
    }
    '/api/admin/debug-auth': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/debug-auth.get').default>>>>
    }
    '/api/admin/delete-image': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/delete-image.delete').default>>>>
    }
    '/api/admin/fix-product-slugs': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/fix-product-slugs.get').default>>>>
    }
    '/api/admin/fix-transactions-table': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/fix-transactions-table.get').default>>>>
    }
    '/api/admin/license-delivery-stats': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/license-delivery-stats.get').default>>>>
    }
    '/api/admin/mass-add': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/mass-add.post').default>>>>
    }
    '/api/admin/overview': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/overview.get').default>>>>
    }
    '/api/admin/product-licenses': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/product-licenses.post').default>>>>
    }
    '/api/admin/product-licenses/use': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/product-licenses/use.post').default>>>>
    }
    '/api/admin/product-names-versions': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/product-names-versions').default>>>>
    }
    '/api/admin/retry-failed-deliveries': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/retry-failed-deliveries.post').default>>>>
    }
    '/api/admin/retry-license-delivery': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/retry-license-delivery.post').default>>>>
    }
    '/api/admin/table-metadata': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/table-metadata.get').default>>>>
    }
    '/api/admin/tables': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/tables.get').default>>>>
    }
    '/api/admin/tables/:table': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/tables/[table].get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/tables/[table].post').default>>>>
    }
    '/api/admin/tables/:table/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/tables/[table]/[id].delete').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/tables/[table]/[id].put').default>>>>
    }
    '/api/admin/tables/massAdd': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/tables/massAdd.post').default>>>>
    }
    '/api/admin/test-email': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/test-email.get').default>>>>
    }
    '/api/admin/transaction-status': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/transaction-status.get').default>>>>
    }
    '/api/admin/transactions': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/transactions.get').default>>>>
    }
    '/api/admin/transactions/stats': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/transactions/stats.get').default>>>>
    }
    '/api/admin/trigger-cleanup': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/trigger-cleanup.post').default>>>>
    }
    '/api/admin/update-category-slugs': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/update-category-slugs.get').default>>>>
    }
    '/api/admin/update-product-slugs': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/update-product-slugs.get').default>>>>
    }
    '/api/admin/update-stock': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/update-stock.post').default>>>>
    }
    '/api/admin/upload-image': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/upload-image.post').default>>>>
    }
    '/api/announcements': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/announcements/index.get').default>>>>
    }
    '/api/categories': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/categories.get').default>>>>
    }
    '/api/checkout/initiate': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/checkout/initiate.post').default>>>>
    }
    '/api/checkout/webhook': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/checkout/webhook.post').default>>>>
    }
    '/api/deals': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/deals/index.get').default>>>>
    }
    '/api/hero-slides': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/hero-slides/index.get').default>>>>
    }
    '/api/home-page-simple': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/home-page-simple.get').default>>>>
    }
    '/api/home-page': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/home-page/index.get').default>>>>
    }
    '/api/login': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/login.post').default>>>>
    }
    '/api/midtrans/notification-with-schema-fixed': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/midtrans/notification-with-schema-fixed.post').default>>>>
    }
    '/api/midtrans/notification-with-schema': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/midtrans/notification-with-schema.post').default>>>>
    }
    '/api/midtrans/notification': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/midtrans/notification.post').default>>>>
    }
    '/api/midtrans/status': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/midtrans/status.get').default>>>>
    }
    '/api/orders/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/orders/[id].get').default>>>>
    }
    '/api/orders/auto-cleanup': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/orders/auto-cleanup.post').default>>>>
    }
    '/api/orders/delete-not-found': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/orders/delete-not-found.post').default>>>>
    }
    '/api/orders/get-license': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/orders/get-license.post').default>>>>
    }
    '/api/orders/get-transaction-id': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/orders/get-transaction-id.post').default>>>>
    }
    '/api/orders': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/orders/index.get').default>>>>
    }
    '/api/orders/process-license': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/orders/process-license.post').default>>>>
    }
    '/api/orders/repay': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/orders/repay.post').default>>>>
    }
    '/api/orders/sync-all': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/orders/sync-all.post').default>>>>
    }
    '/api/orders/update-status': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/orders/update-status.post').default>>>>
    }
    '/api/payment/auto-process-license': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/payment/auto-process-license.post').default>>>>
    }
    '/api/products': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/products.get').default>>>>
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/products/index').default>>>>
    }
    '/api/products/:slug': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/products/[slug].get').default>>>>
    }
    '/api/products/checkout': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/products/checkout.get').default>>>>
    }
    '/api/products/detail': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/products/detail').default>>>>
    }
    '/api/products/details': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/products/details.get').default>>>>
    }
    '/api/products/group/:slug': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/products/group/[slug].get').default>>>>
    }
    '/api/products/stock/:id-fixed': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/products/stock/[id]-fixed.get').default>>>>
    }
    '/api/products/stock/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/products/stock/[id].get').default>>>>
    }
    '/api/profile/change-password': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/profile/change-password.post').default>>>>
    }
    '/api/profile': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/profile/index.get').default>>>>
    }
    '/api/profile/transactions/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/profile/transactions/[id].get').default>>>>
    }
    '/api/profile/transactions/get-license': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/profile/transactions/get-license.post').default>>>>
    }
    '/api/profile/update': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/profile/update.post').default>>>>
    }
    '/api/register': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/register.post').default>>>>
    }
    '/api/search': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/search/index.get').default>>>>
    }
    '/api/setup-missing-tables': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/setup-missing-tables.get').default>>>>
    }
    '/api/transactions/license-status/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/transactions/license-status/[id].get').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}